### ISSUE TITLE
Panic collecting metrics against FRR 7.5.1

### ISSUE THREAD

**Issue by bewing** [tynany/frr_exporter#35]
Release 0.2.15 dies when scraping metrics:

```
$ frr_exporter-0.2.15.linux-amd64/frr_exporter --no-collector.ospf
INFO[0000] Starting frr_exporter (version=, branch=, revision=) on :9342  source="frr_exporter.go:126"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x8f13ab]

goroutine 21 [running]:
github.com/tynany/frr_exporter/collector.execVtyshCommand(0xc000050d00, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/frr_exporter/collector/command.go:26 +0x11b
github.com/tynany/frr_exporter/collector.getBGPSummary(0xa2d104, 0x4, 0xa2dfc8, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/frr_exporter/collector/bgp.go:314 +0x12b
github.com/tynany/frr_exporter/collector.collectBGP(0xc000065800, 0xa2d104, 0x4)
        /root/frr_exporter/collector/bgp.go:281 +0x86
github.com/tynany/frr_exporter/collector.(*BGPCollector).Collect(0xeee1a0, 0xc000065800)
        /root/frr_exporter/collector/bgp.go:71 +0x40
github.com/tynany/frr_exporter/collector.runCollector(0xc000065800, 0xc000014500, 0xc00008ea00, 0xc0000279d0)
        /root/frr_exporter/collector/collector.go:140 +0xc7
created by github.com/tynany/frr_exporter/collector.(*Exporters).Collect
        /root/frr_exporter/collector/collector.go:109 +0x1db
```

0.2.14 does not, but complains about BFD:

```
frr_exporter-0.2.14.linux-amd64/frr_exporter --no-collector.ospf
INFO[0000] Starting frr_exporter (version=0.2.14, branch=HEAD, revision=33efb682dcedee2b8e22d9b5b43c5335a770831b) on :9342  source="frr_exporter.go:121"
ERRO[0002] collector "bfd" scrape failed: cannot unmarshal bfd peers json: unexpected end of JSON input  source="collector.go:144"
```

**Comment by tynany** [comment]
Can you please post your frr.conf?

**Comment by bewing** [comment]
Spun up an EC2 instance of Ubuntu for a simple test case.  
Installed FRR from https://deb.frrouting.org/
```
root@ip-10-233-1-178:~# dpkg --list | grep frr
ii  frr                              7.5.1-0~ubuntu20.04               amd64        FRRouting suite of internet protocols (BGP, OSPF, IS-IS, ...)
ii  frr-pythontools                  7.5.1-0~ubuntu20.04               all          FRRouting suite - Python tools
```
frr_exporter dies with no config:
```
2021-07-29 15:15:01 (13.3 MB/s) - ‘frr_exporter-0.2.15.linux-amd64.tar.gz’ saved [7476769/7476769]

root@ip-10-233-1-178:~# tar -xvzf frr_exporter-0.2.15.linux-amd64.tar.gz
frr_exporter-0.2.15.linux-amd64/
frr_exporter-0.2.15.linux-amd64/frr_exporter
root@ip-10-233-1-178:~# frr_exporter-0.2.15.linux-amd64/frr_exporter
INFO[0000] Starting frr_exporter (version=0.2.15, branch=HEAD, revision=89e71aeaf23a8417fc011c9f85e998a4f28dc888) on :9342  source="frr_exporter.go:126"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x8eb37b]

goroutine 20 [running]:
github.com/tynany/frr_exporter/collector.execVtyshCommand(0xc000189d00, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0)
        /app/collector/command.go:26 +0x11b
github.com/tynany/frr_exporter/collector.getBGPSummary(0xa25f44, 0x4, 0xa26e08, 0x7, 0x0, 0x0, 0x0, 0xc000043da0, 0x413923)
        /app/collector/bgp.go:314 +0x12b
github.com/tynany/frr_exporter/collector.collectBGP(0xc000057800, 0xa25f44, 0x4)
        /app/collector/bgp.go:281 +0x86
github.com/tynany/frr_exporter/collector.(*BGPCollector).Collect(0xee1f20, 0xc000057800)
        /app/collector/bgp.go:71 +0x40
github.com/tynany/frr_exporter/collector.runCollector(0xc000057800, 0xc000012500, 0xc00008aa00, 0xc000023850)
        /app/collector/collector.go:140 +0xc7
created by github.com/tynany/frr_exporter/collector.(*Exporters).Collect
        /app/collector/collector.go:109 +0x1db
root@ip-10-233-1-178:~# cat /etc/frr/frr.conf
# default to using syslog. /etc/rsyslog.d/45-frr.conf places the log
# in /var/log/frr/frr.log
log syslog informational
root@ip-10-233-1-178:~#
```

**Comment by bewing** [comment]
It will also crash if I add a basic BGP config, and disable the OSFP and BFD pollers:

```
root@ip-10-233-1-178:~# frr_exporter-0.2.15.linux-amd64/frr_exporter --no-collector.ospf --no-collector.bfd
INFO[0000] Starting frr_exporter (version=0.2.15, branch=HEAD, revision=89e71aeaf23a8417fc011c9f85e998a4f28dc888) on :9342  source="frr_exporter.go:126"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x8eb37b]

goroutine 20 [running]:
github.com/tynany/frr_exporter/collector.execVtyshCommand(0xc000186d00, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0)
        /app/collector/command.go:26 +0x11b
github.com/tynany/frr_exporter/collector.getBGPSummary(0xa25f44, 0x4, 0xa26e08, 0x7, 0x0, 0x0, 0x0, 0xc000043da0, 0x413923)
        /app/collector/bgp.go:314 +0x12b
github.com/tynany/frr_exporter/collector.collectBGP(0xc000059800, 0xa25f44, 0x4)
        /app/collector/bgp.go:281 +0x86
github.com/tynany/frr_exporter/collector.(*BGPCollector).Collect(0xee1f20, 0xc000059800)
        /app/collector/bgp.go:71 +0x40
github.com/tynany/frr_exporter/collector.runCollector(0xc000059800, 0xc000012500, 0xc00008aa00, 0xc000023850)
        /app/collector/collector.go:140 +0xc7
created by github.com/tynany/frr_exporter/collector.(*Exporters).Collect
        /app/collector/collector.go:109 +0x1db
root@ip-10-233-1-178:~# cat /etc/frr/frr.conf
frr version 7.5.1
frr defaults traditional
hostname ip-10-233-1-178
log syslog informational
no ip forwarding
no ipv6 forwarding
service integrated-vtysh-config
!
router bgp 65432
 neighbor 192.0.2.1 remote-as 65432
!
line vty
!
```

**Comment by fdomain** [comment]
It is due to a nil pointer (fixed by #33), exporter crashes if these in no `--frr.vtysh.pathspace`

**Comment by stefreak** [comment]
I think work around is to provide empty pathspace like --frr.vtysh.pathspace=""

**Comment by tynany** [comment]
Fixed in https://github.com/tynany/frr_exporter/releases/tag/v0.2.16 thanks to @stefreak
