### ISSUE TITLE
bgpl2vpn collector panics due to null prometheus descriptions

### ISSUE THREAD

**Issue by irregulator** [tynany/frr_exporter#56]
Hello and thanks for developing this exporter!

`bgpl2vpn` collector causes panic to the exporter like:

```
ubuntu@removeme2:~$ sudo ./frr_exporter --log.level=debug --no-collector.ospf --no-collector.bfd --collector.bgpl2vpn --co
llector.bgp                                                  
level=info ts=2021-12-13T11:29:56.653Z caller=frr_exporter.go:65 msg="Starting frr_exporter" version="(version=, branch=master, revision=88e396e1a2c57820970ab7b09a76e218f54a9f4a)"
level=info ts=2021-12-13T11:29:56.653Z caller=frr_exporter.go:66 msg="Build context" build_context="(go=go1.16.10, user=, date=)"
level=info ts=2021-12-13T11:29:56.653Z caller=frr_exporter.go:67 msg="Listening on address" address=:9342
level=info ts=2021-12-13T11:29:56.653Z caller=tls_config.go:191 msg="TLS is disabled." http2=false
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x7f0b46]

goroutine 30 [running]:
github.com/prometheus/client_golang/prometheus.NewConstMetric(0x0, 0x2, 0x0, 0xc0000d78c0, 0x4, 0x4, 0xc000103860, 0x1, 0xc0001815f0, 0x93c760)
        /go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/value.go:88 +0x26
github.com/prometheus/client_golang/prometheus.MustNewConstMetric(...)
        /go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/value.go:105
github.com/tynany/frr_exporter/collector.newGauge(0xc0000206c0, 0x0, 0x0, 0xc0000d78c0, 0x4, 0x4)
        /app/collector/collector.go:146 +0x76
github.com/tynany/frr_exporter/collector.processBGPSummary(0xc0000206c0, 0xc0001c4000, 0x2d3, 0x2d3, 0x9f9160, 0x5, 0x9f86ae, 0x4, 0xa9eae0, 0xc000081220, ...)
        /app/collector/bgp.go:194 +0x43a
github.com/tynany/frr_exporter/collector.collectBGP(0xc0000206c0, 0x9f9160, 0x5, 0xa9eae0, 0xc000081220, 0xc00017da40, 0x0, 0x0)
        /app/collector/bgp.go:164 +0x1fb
github.com/tynany/frr_exporter/collector.(*bgpL2VPNCollector).Update(0xc0000a3470, 0xc0000206c0, 0xdd6360, 0x0)
        /app/collector/bgp.go:103 +0x77
github.com/tynany/frr_exporter/collector.runCollector(0xc0000206c0, 0xc0000ad3f0, 0x8, 0xa9ece0, 0xc0000a3470, 0xc000024624, 0xa9eae0, 0xc000080fa0)
        /app/collector/collector.go:115 +0xb8
created by github.com/tynany/frr_exporter/collector.(*Exporter).Collect
        /app/collector/collector.go:106 +0x1a5
```

The FRR configuration merely enables `l2vpn` and looks like this:
```
root@removeme2:~# cat /etc/frr/frr.conf 
# default to using syslog. /etc/rsyslog.d/45-frr.conf places the log
# in /var/log/frr/frr.log
log syslog debug
router bgp 65199
  no bgp default ipv4-unicast
  bgp router-id 1.1.1.1
  neighbor fabric peer-group
  neighbor fabric remote-as 65199
  neighbor fabric capability extended-nexthop
  neighbor 1.2.3.4 peer-group fabric
  !
  address-family l2vpn evpn
   neighbor fabric activate
   advertise-all-vni
  exit-address-family
  !
!
```

The frr_exporter in use has been built out of 88e396e1a2c57820970ab7b09a76e218f54a9f4a commit.

To my understanding, the cause of the panic is that `bgpDesc["ribCount"]` (and the rest of bgpDesc prometheus metrics description [here](https://github.com/tynany/frr_exporter/blob/master/collector/bgp.go#L194)) is null. The regression is probably related to changes of 120ff2ab06679060640610f2765633c672f8c944.

Perhaps, `processBGPSummary` shouldn't be used at all for `l2vpn` address family? And use `processBgpL2vpnEvpnSummary` instead? 

I'll be happy to assist in any way I can.

**Comment by tynany** [comment]
Fixed in https://github.com/tynany/frr_exporter/releases/tag/v1.0.1

**Comment by irregulator** [comment]
Thanks!
